name: Build and Deploy Calculateur SMPH

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    if: github.event_name == 'pull_request'
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build --build-arg SHA=${{ github.sha }} -t smph .
      - name: Running container
        run: |
          docker run -d --name smph -p 8080:80 smph
      - name: Wait for Apache
        run: sleep 2
      - name: Test title
        run: |
          curl -s http://localhost:8080/version.txt | grep -q ${{ github.sha }}
      - name: Stop container
        run: |
          docker stop smph

  build_and_push_to_docker_hub:
    if: github.event_name == 'push'
    name: Build Docker Image with tags
    runs-on: ubuntu-latest
    outputs:
      previous_sha: ${{ steps.get_sha.outputs.previous_sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get previous SHA
        id: get_sha
        run: echo "previous_sha=$(git log --skip=1 -1 --format='%H')" >> $GITHUB_OUTPUT
      - name: Build Docker image
        run: |
          docker build --build-arg SHA=fakesha -t ${{ secrets.DOCKERHUB_USERNAME }}/smph:sha-${{ github.sha }} -t ${{ secrets.DOCKERHUB_USERNAME }}/smph:latest .
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/smph:sha-${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/smph:latest

  trigger_watchtower:
    if: github.event_name == 'push'
    needs: build_and_push_to_docker_hub
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy via n8n
        run: |
          curl -H "Content-Type: application/json" "https://n8n.gcourtot.fr/webhook/${{ secrets.N8N_WEBHOOK_ID }}"
  
  test_prod:
    if: github.event_name == 'push'
    needs: trigger_watchtower
    runs-on: ubuntu-latest
    steps:
      - name: Wait for watchtower
        run: sleep 30
      - name: Test version
        run: |
          for i in {1..10}; do
            curl -sf https://smph.gcourtot.fr/version.txt | grep -q ${{ github.sha }} && exit 0
            sleep 10
          done
          exit 1
          
          
      
  trigger_rollback:
    needs: [test_prod, build_and_push_to_docker_hub]
    if: always() && needs.test_prod.result == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Rollback image
        run: |
          PREVIOUS_SHA=${{ needs.build_and_push_to_docker_hub.outputs.previous_sha }}
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/smph:sha-$PREVIOUS_SHA
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/smph:sha-$PREVIOUS_SHA ${{ secrets.DOCKERHUB_USERNAME }}/smph:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/smph:latest
      - name: Trigger deploy via n8n
        run: |
          curl -H "Content-Type: application/json" "https://n8n.gcourtot.fr/webhook/${{ secrets.N8N_WEBHOOK_ID }}"
